name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - "*"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.6.1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ChangeCast
        uses: palmerhq/changecast@v1.0.0

      - name: Changelog Generator
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
